import type { LucideProps } from 'lucide-react';
import {
  LayoutDashboard,
  Dumbbell,
  BookCopy,
  Clock,
  BarChart3,
  Weight,
  Cog,
  Plus,
  MoreVertical,
  ChevronDown,
  Flame,
  Star,
  Zap,
  PartyPopper,
  Award,
  Trophy,
} from 'lucide-react';

export const Icons = {
  Logo: (props: LucideProps) => <Dumbbell {...props} />,
  Dashboard: LayoutDashboard,
  Routines: BookCopy,
  History: Clock,
  Progress: BarChart3,
  Exercises: Weight,
  Settings: Cog,
  Add: Plus,
  More: MoreVertical,
  ChevronDown,
  Flame,
  Star,
  Zap,
  PartyPopper,
  Award,
  Trophy,
};
